version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "81:81"
      - "82:82"
      - "83:83"
      - "84:84"
      - "85:85"
      - "86:86"
      - "87:87"
      - "88:88"
      - "89:89"
      - "90:90"
      - "93:93"
      - "94:94"
      - "95:95"
      - "96:96"
      - "97:97"
      - "98:98"
      - "99:99"
      - "901:901"
      - "902:902"
      - "903:903"
      - "904:904"
      - "905:905"
      - "906:906"
      - "907:907"
      - "908:908"
      - "909:909"
      - "443:443"
    volumes:
#      - ./www/:/var/www/html/:rw
      - /Users/chunguanghao/Documents/ofashion/projects/:/Users/chunguanghao/Documents/ofashion/projects/:rw
#      - ./conf/conf.d:/etc/nginx/conf.d/:rw
      - /Users/chunguanghao/Documents/ofashion/docker.nginx.conf.d:/etc/nginx/conf.d/:rw
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/fastcgi_params:/etc/nginx/fastcgi_params:ro
#      - ./log/:/var/log/dnmp/:rw
      - ./log//:/var/log/nginx/:rw
    restart: always
    networks:
      - net-php
      - net-php72
      - net-php56
      - net-php54

  php:
    build:
      context: .
      args:
        PHP_VERSION: 7.2
        SOURCE_LIST: stretch
        XDEBUG_VERSION: 2.6.1
        SWOOLE_VERSION: 4.2.1
        SUPPORT_MCRYPT: "false"
        BUILT_IN_OPCACHE: "true"
    expose:
      - "9000"
    volumes:
      - /Users/chunguanghao/Documents/ofashion/projects/:/Users/chunguanghao/Documents/ofashion/projects/:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/:/var/log/dnmp/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - net-php
      - net-mysql
      - net-redis

  php72:
    build:
      context: .
      args:
        PHP_VERSION: 7.2
        SOURCE_LIST: stretch
        XDEBUG_VERSION: 2.6.1
        SWOOLE_VERSION: 4.2.1
        SUPPORT_MCRYPT: "false"
        BUILT_IN_OPCACHE: "true"
    expose:
      - "9000"
    volumes:
      - /Users/chunguanghao/Documents/ofashion/projects/:/Users/chunguanghao/Documents/ofashion/projects/:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/:/var/log/dnmp/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - net-php72
      - net-mysql
      - net-redis

  php56:
    build:
      context: .
      args:
        PHP_VERSION: 5.6
        SOURCE_LIST: jessie
        XDEBUG_VERSION: 2.5.5
        SWOOLE_VERSION: 2.0.11
        SUPPORT_MCRYPT: "true"
        BUILT_IN_OPCACHE: "true"
    expose:
      - "9000"
    volumes:
      - /Users/chunguanghao/Documents/ofashion/projects/:/Users/chunguanghao/Documents/ofashion/projects/:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/:/var/log/dnmp/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - net-php56
      - net-mysql
      - net-redis

  php54:
    build:
      context: .
      args:
        PHP_VERSION: 5.4
        SOURCE_LIST: jessie
        XDEBUG_VERSION: 2.4.1
        SWOOLE_VERSION: "false"
        SUPPORT_MCRYPT: "true"
        BUILT_IN_OPCACHE: "false"
    expose:
      - "9000"
    volumes:
      - /Users/chunguanghao/Documents/ofashion/projects/:/Users/chunguanghao/Documents/ofashion/projects/:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/:/var/log/dnmp/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - net-php54
      - net-mysql
      - net-redis

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
    restart: always
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  redis:
    image: redis:4.0
    restart: always
    networks:
      - net-redis
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - net-mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - "8081:80"
    networks:
      - net-redis
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379

networks:
  net-php:
  net-php72:
  net-php56:
  net-php54:
  net-mysql:
  net-redis:
