version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "81:81"
      - "82:82"
      - "83:83"
      - "84:84"
      - "85:85"
      - "86:86"
      - "87:87"
      - "88:88"
      - "89:89"
      - "90:90"
      - "93:93"
      - "94:94"
      - "95:95"
      - "96:96"
      - "97:97"
      - "98:98"
      - "99:99"
      - "901:901"
      - "902:902"
      - "903:903"
      - "904:904"
      - "905:905"
      - "906:906"
      - "907:907"
      - "908:908"
      - "909:909"
      - "443:443"
    volumes:
#      - ./www/:/var/www/html/:rw
      - /Users/chunguanghao/Documents/ofashion/projects/:/Users/chunguanghao/Documents/ofashion/projects/:rw
#      - ./conf/conf.d:/etc/nginx/conf.d/:rw
      - /Users/chunguanghao/Documents/ofashion/docker.nginx.conf.d:/etc/nginx/conf.d/:rw
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/fastcgi_params:/etc/nginx/fastcgi_params:ro
#      - ./log/:/var/log/dnmp/:rw
      - ./log/:/var/log/nginx/:rw
    restart: always
    networks:
      - net-php56


  php:
    build:
      context: .
      args:
        PHP_VERSION: 5.6
        SOURCE_LIST: jessie
        XDEBUG_VERSION: 2.5.5
        SWOOLE_VERSION: 2.0.11
        SUPPORT_MCRYPT: "true"
        BUILT_IN_OPCACHE: "true"
    expose:
      - "9000"
    volumes:
      - /Users/chunguanghao/Documents/ofashion/projects/:/Users/chunguanghao/Documents/ofashion/projects/:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/:/var/log/dnmp/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - net-php56

networks:
  net-php56:
